config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :update, :edit, :index] do
    member do
      get 'notifications'
      get 'refresh'
    end
    resources :friendships, :only => [:index, :create, :update, :destroy] do
      collection do
        get 'search_friends'
        get 'search'
        get 'pendings'
        post 'invite'
      end
    end
    resources :bets, :only => [:create, :new, :index] 
    resources :bet_participations, :only => [:update, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :bets, :only => [:show, :edit, :update] do
    resources :comments, only: [:create, :new, :show]
    member do
      get 'summary'
    end
    get 'community', on: :collection
    get 'pending', on: :collection
    get 'inplay', on: :collection
    get 'completed', on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  root :to => 'users#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :user_id, :bet_id, :text

  belongs_to(
  :author,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  belongs_to(
  :bet,
  class_name: "Bet",
  foreign_key: :bet_id,
  primary_key: :id
  )

  def time_since_last_update
    age = Time.now()-self.updated_at
    if age > 259200
      return self.updated_at.strftime("on %B %e, %Y at %-I:%M%P")
    elsif age > 172800
      return (age / 86400).floor.to_s + " days ago"
    elsif age > 86400
      return self.updated_at.strftime("yesterday at %-I:%M%P")
    elsif age > 3600
      return (age / 3600).floor.to_s + " hours ago"
    else age
      return (age / 60).floor.to_s + " minutes ago"
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    puts "------------------"
    puts params
    @comment = Comment.new(params[:comment])
    @comment.bet_id = params[:bet_id]
    @comment.user_id = current_user.id
    if @comment.save
      @comment.bet.commenters.each do |commenter|

        next if @comment.author == commenter

        if @comment.bet.participants.include?(commenter)
          Notification.create(user_id: commenter.id, text: "#{@comment.author.abbrev_name}. also commented on a bet that you're in with #{@comment.bet.author.abbrev_name}.", link: bet_url(@comment.bet))
        else
          Notification.create(user_id: commenter.id, text: "#{@comment.author.abbrev_name}. also commented on #{@comment.bet.author.abbrev_name}.'s bet", link: bet_url(@comment.bet))
        end
      end
      @comment.bet.participants.each do |participant|
        next if @comment.author == participant || @comment.bet.commenters.include?(participant)
        Notification.create(user_id: participant.id, text: "#{@comment.author.abbrev_name}. also commented on #{@comment.bet.author.abbrev_name}.'s bet", link: bet_url(@comment.bet))
      end

      render partial: 'comments/show', locals: {comment: @comment}

    else
      render :json => "Could not save comment"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_expanded_comments_form.html.erb
<div class="comments-section">
  <div class="uparrow-comments"></div>
  <ul class="comments-list">
  <% bet.comments.each do |comment| %>
  <li class="comment group">
    <div class="comment-thumb"><%= image_tag comment.author.profile_pic.url(:thumb), :class => "comment-pic" %>
    </div>

    <div class="comment-content">
      <div class="comment-text"><span class="link-name"><a href="<%= user_url(comment.user_id) %>" data-remote="true"><%= comment.author.full_name %></a></span>: <%= comment.text %></div>
      <time class="comment-time"><%= comment.time_since_last_update %></time>
    </div>
  </li>
  <% end %>
  </ul>

  <div class="new-comment">
    <div class="new-comment-thumb"><%= image_tag current_user.profile_pic.url(:thumb), :class => "comment-pic" %></div>
    <form id="new-comment-form" action="<%= bet_comments_url(bet.id) %>" method="post">
    <input
       name="authenticity_token"
       type="hidden"
       value="<%= form_authenticity_token %>">

    <textarea rows="1" cols="50" name="comment[text]" placeholder="write a comment" ></textarea>
  </form>

</div>

app/views/comments/_show.html.erb
<li class="comment group">
  <div class="comment-thumb"><%= image_tag comment.author.profile_pic.url(:thumb), :class => "comment-pic" %>
  </div>

  <div class="comment-content">
    <div class="comment-text"><span class="link-name"><a href="<%= user_url(comment.user_id) %>"><%= comment.author.full_name %></a></span>: <%= comment.text %></div>
    <time class="comment-time"><%= comment.time_since_last_update %></time>
  </div>
</li>