config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :update, :edit, :index] do
    member do
      get 'notifications'
      get 'refresh'
    end
    resources :friendships, :only => [:index, :create, :update, :destroy] do
      collection do
        get 'search_friends'
        get 'search'
        get 'pendings'
        post 'invite'
      end
    end
    resources :bets, :only => [:create, :new, :index] 
    resources :bet_participations, :only => [:update, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :bets, :only => [:show, :edit, :update] do
    resources :comments, only: [:create, :new, :show]
    member do
      get 'summary'
    end
    get 'community', on: :collection
    get 'pending', on: :collection
    get 'inplay', on: :collection
    get 'completed', on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  root :to => 'users#index'
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  attr_accessible :private, :status, :terms, :user_id, :wager, :participant_ids, :participants
  validates :status, :terms, :user_id, presence: true
  validates :status, :inclusion => {:in => ['pending', 'in play', 'completed', 'cancelled']}
  validates :private, :inclusion => {:in => [true, false]}
  before_save :set_default_status_pending

  belongs_to(
  :author,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  has_many(
  :participations,
  class_name: "BetParticipation",
  foreign_key: :bet_id,
  primary_key: :id
  )

  has_many :participants, :through => :participations, source: :participant
  #has_many :participants_ex_author, :through => :participations, source: :participant, :conditions => ['users.id = ?', '#{self.user_id}']
  has_many :accepted_participants, :through => :participations, source: :participant, :conditions => ['bet_participations.status = ?', 'accepted']
  has_many :pending_participants, :through => :participations, source: :participant, :conditions => ['bet_participations.status = ?', 'pending']

  has_many(
  :comments,
  class_name: "Comment",
  foreign_key: :bet_id,
  primary_key: :id
  )

  has_many :commenters, :through => :comments, source: :author, :uniq => true

  has_many(
  :winning_entries,
  class_name: "WinnerEntry",
  foreign_key: :bet_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many(
  :losing_entries,
  class_name: "LoserEntry",
  foreign_key: :bet_id,
  primary_key: :id,
  dependent: :destroy
  )

  has_many :winners, :through => :winning_entries, source: :winner
  has_many :losers, :through => :losing_entries, source: :loser

  def all_participants_accepted?
    participations.all? { |participation| participation.status == "accepted" }
  end

  def participation_author
    participations.select { |participation| participation.user_id == self.author.id }
  end

  def participants_ex_author
    participants.select { |participant| participant != self.author }
  end

  def participations_ex_author
    participations.select { |participation| participation.user_id != self.author.id }
  end
  
  def bet_summary
    challengers = self.participants_ex_author
    summary = "#{self.author.full_name} bet"
    if challengers.count == 1
      summary += " #{challengers[0].full_name}"
    elsif challengers.count 2
      summary += " #{challengers[0].full_name} and #{challengers[1].full_name}"
    else
      challengers.each_with_index do |challenger, index|
        if index == challengers.length - 1
          summary += " and #{challenger.full_name}"
        else
          summary += " #{challenger.full_name},"
        end
      end
    end
    
    summary += " that #{self.terms}. Loser(s) has to #{self.wager}."
    
    case self.status
    when "pending"
      summary += " This bet is still pending."
    when "in play"
      summary += " This bet is LIVE!"
    when "completed"
      summary += " This bet is OVER.\nWinner(s):#{self.winners_summary}\nLoser(s):#{self.losers_summary}"
    when "cancelled"
      summary += " This bet has been cancelled."
    end
    
    summary
  end
  
  def winners_summary
    winners = self.winners
    summary = ""
    if winners.empty?
      return " None"
    else
      if winners.count == 1
        return " #{winners[0].full_name}"
      elsif winners.count 2
        return " #{winners[0].full_name} and #{winners[1].full_name}"
      else
        winners.each_with_index do |winner, index|
          if index == winners.length - 1
            summary += " and #{winner.full_name}"
          else
            summary += " #{winner.full_name},"
          end
        end
      end
    end
    
    summary
  end
  
  def losers_summary
    losers = self.losers
    summary = ""
    if losers.empty?
      return " None"
    else
      if losers.count == 1
        return " #{losers[0].full_name}"
      elsif losers.count 2
        return " #{losers[0].full_name} and #{losers[1].full_name}"
      else
        losers.each_with_index do |loser, index|
          if index == losers.length - 1
            summary += " and #{loser.full_name}"
          else
            summary += " #{loser.full_name},"
          end
        end
      end
    end
    
    summary
  end

  def time_since_last_update
    age = Time.now()-self.updated_at
    if age > 259200
      return self.updated_at.strftime("on %B %e, %Y at %-I:%M%P")
    elsif age > 172800
      return (age / 86400).floor.to_s + " days ago"
    elsif age > 86400
      return self.updated_at.strftime("yesterday at %-I:%M%P")
    elsif age > 3600
      return (age / 3600).floor.to_s + " hours ago"
    else age
      return (age / 60).floor.to_s + " minutes ago"
    end
  end
  
  

  def set_default_status_pending
    if !self.status
      self.status = "pending"
    end
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_filter :require_current_user!, :only => [:community, :pending, :inplay, :completed]
  before_filter :require_admin_access!, :only => [:create, :new, :index]
  before_filter :require_bet_participant!, :only => [:edit, :update]

  def create
    @bet = Bet.new(params[:bet])
    @bet.user_id = current_user.id
    @bet.status = "in play" if !params[:challenge]
    if @bet.save
      # Temporarily disabled inviting new users via email.
      # new_user_emails = parse_new_users(params[:new_user_emails])
#       new_user_emails.each do |new_user_email|
#         user = User.find_by_username(new_user_email)
#         if user
#           params[:bet_participation][:user_id] << user.id
#         else
#           new_user = User.create(username: new_user_email)
#           invite_email = UserMailer.invite_challenge_email(new_user, current_user)
#           invite_email.deliver!
#           params[:bet_participation][:user_id] << new_user.id
#         end
#       end

    
      BetParticipation.create(bet_id: @bet.id, user_id: current_user.id, status: "accepted")
      params[:bet_participation][:user_id].each do |participant_id|
        next if participant_id == ""
        if params[:challenge]
          BetParticipation.create(bet_id: @bet.id, user_id: participant_id.to_i, status: "pending")
          Notification.create(user_id: participant_id.to_i, text: "#{@bet.author.abbrev_name}. has challenged you to a bet! (action needed)", link: bet_url(@bet))
        else
          BetParticipation.create(bet_id: @bet.id, user_id: participant_id.to_i, status: "accepted")
          Notification.create(user_id: participant_id.to_i, text: "#{@bet.author.abbrev_name}. has added you to a bet!", link: bet_url(@bet))
        end
      end
      
    else
      render :json => "Unable to save bet"
    end
    
    if request.xhr?
      render partial: 'bets/show_details_lightbox', locals: {bet: @bet}
    else
      render partial: 'bets/show_details_lightbox', locals: {bet: @bet}
    end
    
  end

  def new
    @bet = Bet.new
    if request.xhr?
      render partial: 'bets/form', locals: {bet: @bet}
    else
      render partial: 'bets/form', locals: {bet: @bet}
    end
  end

  def index
  end

  def show
    @bet = Bet.find(params[:id])
    require_bet_participant! if @bet.private
    if request.xhr?
      render partial: 'bets/show_details_lightbox', locals: {bet: @bet}
    else
      render partial: 'bets/show_details_lightbox', locals: {bet: @bet}
    end
  end

  def edit
    @bet = Bet.find(params[:id])
    if request.xhr?
      render partial: 'bets/form', locals: {bet: @bet}
    else
      render partial: 'bets/form', locals: {bet: @bet}
    end
  end

  #need its own permission check, sicne there is no user_id
  def update
    participant_ids = params[:bet_participation][:user_id]
    winner_ids = params[:bet_winner][:user_id]
    loser_ids = params[:bet_loser][:user_id]

    @bet = Bet.find(params[:id])
    if @bet.update_attributes( params[:bet] )
      @bet.update_attributes( private: false ) if !params[:bet][:private]
      #first destroy any old participants that isn't in the new set
      update_participants(@bet, participant_ids)
      update_winners(@bet, winner_ids)
      update_losers(@bet, loser_ids)
      
      @bet.participants.each do |participant|
        unless participant == current_user
          Notification.create(user_id: participant.id, text: "#{current_user.abbrev_name}. has edited a bet that you're in", link: bet_url(@bet))
        end
      end
    else
      flash[:error] = "Unable to update bet"
    end
    
    if request.xhr?
      render partial: 'bets/bet_detail', locals: {bet: @bet}
    else
      render partial: 'bets/bet_detail', locals: {bet: @bet}
    end

  end

  def summary
    @bet = Bet.find(params[:id])
    require_bet_participant! if @bet.private
    puts @bet.bet_summary
    
    render :json => @bet.bet_summary.to_json
  end

  def community
    @user = current_user
    #@bets = current_user.bets.where( status: 'in play' )
    @bets = @user.community_bets
    @bets = Kaminari.paginate_array(@bets).page(params[:page]).per(5)

    if request.xhr?
      render partial: 'bets/display_bets'
    else
      render :feed
    end
  end

  def pending
    @user = current_user
    @bets = current_user.pending_bets
    @bets = Kaminari.paginate_array(@bets).page(params[:page]).per(5)
    if request.xhr?
      render partial: 'bets/display_bets', locals: {bets: @bets}
    else
      render :feed
    end
  end

  def inplay
    @user = current_user
    @bets = current_user.inplay_bets
    @bets = Kaminari.paginate_array(@bets).page(params[:page]).per(5)
    if request.xhr?
      render partial: 'bets/display_bets', locals: {bets: @bets}
    else
      render :feed
    end
  end

  def completed
    @user = current_user
    @bets = current_user.completed_bets
    @bets = Kaminari.paginate_array(@bets).page(params[:page]).per(5)
    if request.xhr?
      render partial: 'bets/display_bets', locals: {bets: @bets}
    else
      render :feed
    end
  end

  private

  def update_participants(bet, participant_ids)
    @bet = bet

    #first delete removed participants
    @bet.participants.each do |participant|
      if !participant_ids.include?(participant.id.to_s) && participant.id != @bet.author.id
        BetParticipation.find_by_bet_id_and_user_id(@bet.id, participant.id).destroy
        Notification.create(user_id: participant.id, text: "You have been removed from a bet", link: bet_url(@bet))
      end
    end

    #then make any more participations that aren't present in the database
    participant_ids.each do |new_participant_id|
      next if new_participant_id == ""
      if @bet.participants.select { |participant| participant.id == new_participant_id.to_i }.empty?
        BetParticipation.create(bet_id: @bet.id, user_id: new_participant_id.to_i, status: "pending")
        Notification.create(user_id: new_participant_id.to_i, text: "#{current_user.abbrev_name}. included you in a bet!", link: bet_url(@bet))
      end
    end
  end

  def update_losers(bet, loser_ids)
    @bet = bet
    
    #first delete removed losers
    @bet.losers.each do |loser|
      if !loser_ids.include?(loser.id.to_s)
        LoserEntry.find_by_bet_id_and_user_id(@bet.id, loser.id).destroy
        Notification.create(user_id: loser.id, text: "Vindication! You have been removed as a loser on a bet", link: bet_url(@bet))
      end
    end
        
    loser_ids.each do |new_loser_id|
      next if new_loser_id == ""
      if @bet.losers.select { |loser| loser.id == new_loser_id.to_i }.empty?
        LoserEntry.create(user_id: new_loser_id.to_i, bet_id: @bet.id)
        Notification.create(user_id: new_loser_id.to_i, text: "#{current_user.abbrev_name}. added you as a loser on a bet", link: bet_url(@bet) )
      end
    end
  end

  def update_winners(bet, winner_ids)
    @bet = bet
    
    @bet.winners.each do |winner|
      if !winner_ids.include?(winner.id.to_s)
        WinnerEntry.find_by_bet_id_and_user_id(@bet.id, winner.id).destroy
        Notification.create(user_id: winner.id, text: "Oh no! #{current_user.abbrev_name} removed you as a winner on a bet", link: bet_url(@bet))
      end
    end
        
    winner_ids.each do |new_winner_id|
      next if new_winner_id == ""
      if @bet.winners.select { |winner| winner.id == new_winner_id.to_i }.empty?
        WinnerEntry.create(user_id: new_winner_id.to_i, bet_id: @bet.id)
        Notification.create(user_id: new_winner_id.to_i, text: "#{current_user.abbrev_name}. added you as a winner to a bet", link: bet_url(@bet) )
      end
    end
  end

  def parse_new_users(users_string)
    return users_string.split(",").map(&:strip)
  end

  def require_bet_participant!
    @bet = Bet.find(params[:id])
    unless @bet.participants.include?(current_user)
      flash[:error] = "You do not have permission for this action"
      if @bet.private
        redirect_to root_url
      else
        redirect_to bet_url(@bet)
      end
    end
  end

end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_accept_button.html.erb
<form class="trigger-bet-invite-response" action="<%= user_bet_participation_url(current_user.id, current_user.find_bet_participation(bet)) %>" data-remote="true" method="post">
 <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

  <input
     name="_method"
     type="hidden"
     value="put">

 <input
    type="hidden"
    name="bet_participation[status]"
    value="accepted">
 <input type="submit" value="Accept">
</form>

app/views/bets/_bet_detail.html.erb
<div class="bet-header group">
  <% bet.participants.each_with_index do |participant, index| %>
    <% unless index == 0 %>
      <%= image_tag("15px-sword-vs.png", class: "vs-pic") %>
    <% end %>
    <%= image_tag participant.profile_pic.url(:thumb), :class => "participant-pic" %>
  <% end %>

  <div class='bet-privacy bet-<%= bet.private ? 'private' : 'public' %>'><%= bet.private ? 'Private' : 'Public' %></div>
  <div class="bet-status">Status: <span class="bet-<%= bet.status.delete(' ') %>"><%= bet.status.split.map(&:capitalize).join(' ') %></span></div>

</div>

<div class="bet-author-pic">
  <%= image_tag bet.author.profile_pic.url(:small), :class => "bet-author-pic" %>
</div>

<div class="bet-content">
  <div class="bet-terms">
    <span class="link-name user-<%= bet.participation_author.first.status %>"><a href="<%= user_url(bet.author) %>" data-remote="true"><%= bet.author.full_name %></a></span> bets
    <% case bet.participations_ex_author.count %>
      <% when 0..1 %>
      <% bet.participations_ex_author.each do |participation| %>
        <span class="link-name user-<%= participation.status %>"><a href="<%= user_url(participation.user_id) %>" data-remote="true"><%= participation.participant_full_name %></a></span>
        <% end %>
        <% when 2 %>
        <span class="link-name user-<%= bet.participations_ex_author.first.status %>"><a href="<%= user_url(bet.participations_ex_author.first.user_id) %>" data-remote="true"><%= bet.participations_ex_author.first.participant_full_name %></a></span> and <span class="link-name user-<%= bet.participations_ex_author.last.status %>"><a href="<%= user_url(bet.participations_ex_author.last.user_id) %>" data-remote="true"><%= bet.participations_ex_author.last.participant_full_name %></a></span>
        <% else %>
      <% bet.participations_ex_author.each_with_index do |participation, index| %>
        <%= "and " if index == bet.participations_ex_author.count-1 %><span class="link-name user-<%= participation.status %>"><a href="<%= user_url(participation.user_id) %>" data-remote="true"><%= participation.participant_full_name %></a></span><%= index == bet.participations_ex_author.count-1 ? " " : ", " %>
        <% end %>
        <% end %>
        that <%= bet.terms %>.<br>
        <br>
        Loser(s) has to <%= bet.wager %>.
  </div>

  <% if bet.status == 'completed' %>
  <div class="winners-losers-section">
    <span class="winner_header">Winner(s):</span>
      <% bet.winners.each_with_index do |winner, index| %>
        <%= winner.abbrev_name %>.<%= ", " unless index == bet.winners.count-1 %>
      <% end %>
      <br>
    <span class="loser_header">Loser(s):</span>
      <% bet.losers.each_with_index do |loser, index| %>
        <%= loser.abbrev_name %>.<%= ", " unless index == bet.losers.count-1 %>
      <% end %>
  </div>
  <% end %>

  <% if current_user.inbound_pending_bets.include?(bet) %>
  <div class="bet-acceptance-section group">
	<div class="bet-acceptance-content group">
		<span class="group">Do you accept this challenge?</span>
		<div class="bet-buttons">
			<div class="bet-accept-button"><%= render "/bets/accept_button", :bet => bet %></div>
			<div class="bet-decine-button"><%= render "/bets/decline_button", :bet => bet %></div>
	</div>
</div>
  </div>
  <% end %>

  <div class="bet-options group">
    <ul>
      <% if bet.participants.include?(current_user) %>
      <li class="trigger-edit-bet-form"><a href="<%= edit_bet_url(bet) %>" data-remote="true">Edit Bet</a></li>
      <% end %>
      <li class="share-bet-fb"><a href="<%= summary_bet_url(bet) %>" data-remote="true" data-type="json">Share</a></li>
      <li><a href="#">Comment</a></li>
      <li>Last updated <%= bet.time_since_last_update %></li>
    </ul>
  </div>

  <%= render "/comments/expanded_comments_form", :bet => bet%>

app/views/bets/_decline_button.html.erb
<form class="trigger-bet-invite-response" action="<%= user_bet_participation_url(current_user.id, current_user.find_bet_participation(bet)) %>" data-remote="true" method="post">
 <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

  <input
     name="_method"
     type="hidden"
     value="put">

 <input
    type="hidden"
    name="bet_participation[status]"
    value="declined">
 <input type="submit" value="Decline">
</form>

app/views/bets/_display_bets.html.erb
<% @bets.each do |bet| %>
<% next if bet.nil? %>
    <li class="bets-list-item" data-id="<%= bet.id %>">
      <%= render "/bets/bet_detail", :bet => bet %>
    </li>
<%end%>

<input type="hidden" class="page-num" value="<%= params[:page] || 1 %>"></input>
<input type="hidden" class="total-pages" value="<%= @bets.total_pages %>"></input>

app/views/bets/_edit_lightbox.html.erb
<div class="edit-bet-form light-box-form hidden" id="edit-bet-form">
  <div class="form-header group" id="form-header">
    <span class="form-title">Edit Bet</span>
    <div class="x-button" id="x-button">x</div>
  </div>
  <div class="form-content group" id="edit-bet-content"></div>
</div>

app/views/bets/_feeds_header.html.erb
<header class="feeds_bar">
  Bet Feeds:
  <ul class="feeds_list">
    <li><%= link_to "Community", community_bets_url %></li>
    <li><%= link_to "Pending", pending_bets_url %></li>
    <li><%= link_to "In-Play", inplay_bets_url %></li>
    <li><%= link_to "Completed", completed_bets_url %></li>
  </ul>
</header>

app/views/bets/_form.html.erb
<script>
$(document).ready(function(){
	if($('#bet_status').val() != 'completed') {
		$('#bet-results-form').addClass('hidden');
	} else {
		$('#bet-results-form').removeClass('hidden');
	}
	
	$('#bet_status').change(function() {
		if($(this).val() != 'completed') {
			$('#bet-results-form').addClass('hidden');
		} else {
			$('#bet-results-form').removeClass('hidden');
		}
	})
	
	$('.bettee-search-area').on('focus', function() {
		console.log("bettee search focused!")
		$('.bettee-search-area').keyup(function(event) {
			console.log("keyup!" + event.which);
			if( (event.which >= 48 && event.which <= 57) || (event.which >= 65 && event.which <= 90) || event.which == 8 || event.which == 32) {
				var that = this
				var url = $(event.currentTarget).attr('url');
				var data = $(event.currentTarget).html();
				$.ajax ({
					method: "GET",
					url: url,
					data: {"query": data},
					success: function(data) {
						if (!data) {
							console.log("no matches!");
							$('.bettee-drop-down').html("");
							$('.bettee-drop-down').addClass('hidden');
						} else {
							console.log("this is the data!");
							console.log($(data).children('li:first-child'));
							var $list = $(data)
							$list.children('li:first-child').addClass("selected");
							$('.bettee-drop-down').html($list);
							$('.bettee-drop-down').removeClass('hidden');
							
							$('.bettee-drop-down ul li').hover(function(event) {
								console.log(event.currentTarget);
								$(event.currentTarget).siblings().removeClass('selected');
								$(event.currentTarget).addClass('selected');
							})
						}
					
					}
				})
			}
		})
		$('.bettee-search-area').keydown(function(event) {
			switch (event.which) {
			case 38:
				console.log("up pressed");
				event.preventDefault();
				console.log($(event.currentTarget).next().find('.selected'));
				$li = $(event.currentTarget).next().find('.selected');
				if ($li.prev().length > 0) {
					$li.removeClass('selected');
					$li.prev().addClass('selected');
				}
				break;			
			case 40:
				console.log("down pressed");
				event.preventDefault();
				$li = $(event.currentTarget).next().find('.selected');
				if ($li.next().length > 0) {
					$li.removeClass('selected');
					$li.next().addClass('selected');
				}
				break;
			case 9:
				console.log("tab pressed");
				//if search box is not empty, find selected.  if it is, tab to next field.
				if ( !($.trim($(event.currentTarget).html()) == "") ) {
					event.preventDefault();
					$li = $(event.currentTarget).next().find('.selected');
					$li.trigger('click');
				}
				break;
			case 13:
				console.log("enter pressed");
				event.preventDefault();
				$li = $(event.currentTarget).next().find('.selected');
				$li.trigger('click');
				break;
			}
			
		})
	})
	
	
	
	//to remove handler once focus is off
	$('.bettee-search-area').on('blur', function() {
		$('.bettee-search-area').off('keyup');
		$('.bettee-search-area').off('keydown');
	})
	
    $('.bettee-drop-down').on('click', 'li', function(event){
		event.preventDefault();
		event.stopPropagation();
		console.log(this)
		var betteeId = $(event.currentTarget).children('a').attr('href').split("/").pop();
		var betteeName = $(event.currentTarget).children('a').html().split(">").pop();
		var $betteeBlock = $('<div></div>');
		$betteeBlock.attr({ class: 'bettee-block', "data-id": betteeId });
		$betteeBlock.html('<span>' + betteeName + '</span><div class="bettee-block-x">x</div>')
		$('.bettee-search-area').before($betteeBlock);
		$('.bettee-drop-down').html("");
		$('.bettee-search-area').html("");
		$('.bettee-drop-down').addClass('hidden');
    })
	
	$('.bettee-drop-down-anchor').on('click', '.bettee-block-x', function(event) {
		event.preventDefault();
		console.log("triggered x!")
		$(event.currentTarget).parent().remove();
	})
	
});





</script>

<% action = (bet.persisted? ? bet_url(bet) : user_bets_url(current_user)) %>
<% method = (bet.persisted? ? "put" : "post") %>
<% message = (bet.persisted? ? "Update Bet" : "Create Bet") %>


<form class="trigger-submit-bet" action="<%= action %>" data-id="<%= bet.id %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">

  <%= current_user.abbrev_name%>. bets

  <div class="bet-participants-section group">
	 Participants: 
	 <div class="bettee-drop-down-anchor">
		 <% if bet.persisted? %>
		 <% bet.participants.each do |participant| %>
		 <% unless participant == bet.author %>
		 <div class="bettee-block" data-id="<%= participant.id %>">
			 <span><%= participant.full_name %> (<%= participant.username %>)</span>
			 <div class="bettee-block-x">x</div>
		 </div>
		 <% end %>
		 <% end %>
		 <% end %>
		 <div class="bettee-search-area" url="<%= search_friends_user_friendships_url(current_user.id) %>" contenteditable>
		 </div>
		   <div class="bettee-drop-down hidden"></div>
	 </div>
 </div>

	<div class="bet-terms-section group">
    that...<br>
	  <textarea name="bet[terms]" placeholder="he/she can run more than 20 miles this week" rows="2" cols="50"><%= bet.terms if bet.persisted? %></textarea>
	</div>
	
	<div class="bet-wager-section group">
  	  Loser(s) has to...<br>
	  <textarea name="bet[wager]" placeholder="wear a shirt of the winner's choosing next time we go out" rows="2" cols="50"><%= bet.persisted? ? bet.wager : "" %></textarea>
	</div>
  
  <div class="bet-privacy-section group">
  <input
    <%= "checked" if bet.private %>
    id="bet_private"
    name="bet[private]"
    value=true
    type="checkbox">
  <label for="bet_private">Private</label>
  </div>

	<% if !bet.persisted? %>
	  <div class="bet-challenging-section group">
	  <input
	    <%= "checked" if bet.private %>
	    id="bet_challenge"
	    name="challenge"
	    value=true
	    type="checkbox">
	  <label for="bet_challenge">Require participants to accept/decline bet</label>
	  </div>
	<% end %>


  <% if bet.persisted? %>
  <div class="bet-status-section group">
  <label for="bet_status">Status: </label>
  <select id="bet_status" name="bet[status]">
    <option value="pending" <%= "selected" if bet.status == "pending" %>>Pending</option>
    <option value="in play" <%= "selected" if bet.status == "in play" %>>In Play</option>
    <option value="completed" <%= "selected" if bet.status == "completed" %>>Completed</option>
    <option value="cancelled" <%= "selected" if bet.status == "cancelled" %>>Cancelled</option>
  </select>
  </div>

  <div id="bet-results-form" class="group">
	  <span class="group">Results:</span>
	  <div class="results-winners-table">
	  Select Winner(s):<br>
	  <input type="hidden" name="bet_winner[user_id][]" value="">
	   <% bet.participants.each do |participant| %>
	     <input
	       id="bet_winner_id_<%= participant.id %>"
	       name="bet_winner[user_id][]"
	       value="<%= participant.id %>"
	       type="checkbox"
		   <%= "checked" if bet.winners.include?(participant) %>>
	     <label for="bet_winner_id_<%= participant.id %>"><%= participant.first_name %> <%= participant.last_name %></label>
	     <br>
	     <% end %>
 	   </div>

	   <div class="results-losers-table">
	   Select Loser(s):<br>
	   <% bet.participants.each do |participant| %>
	   <input type="hidden" name="bet_loser[user_id][]" value="">
	     <input
	       id="bet_loser_id_<%= participant.id %>"
	       name="bet_loser[user_id][]"
	       value="<%= participant.id %>"
	       type="checkbox" 
		   <%= "checked" if bet.losers.include?(participant) %>>
	     <label for="bet_loser_id_<%= participant.id %>"><%= participant.first_name %> <%= participant.last_name %></label>
	     <br>
	     <% end %>
	   </div>
 </div>

  <% end %>

  <input type="submit" value="<%= message %>">
</form>

app/views/bets/_new_lightbox.html.erb
<div class="new-bet-form light-box-form hidden" id="new-bet-form">
  <div class="form-header group" id="form-header">
    <span class="form-title">New Bet</span>
    <div class="x-button" id="x-button">x</div>
  </div>
  <div class="form-content group" id="new-bet-content"></div>
</div>

app/views/bets/_show_details_lightbox.html.erb
<ul class="bets-list">
	<li class="bets-list-item" data-id="<%= bet.id %>">
    	<%= render "/bets/bet_detail", :bet => bet %>
	</li>
</ul>

app/views/bets/_show_lightbox.html.erb
<div class="bet-show-form light-box-form hidden" id="bet-show-form">
  <div class="form-header group" id="form-header">
    <span class="form-title">Bet Show Page</span>
    <div class="x-button" id="x-button">x</div>
  </div>
  <div class="form-content group" id="bet-show-content">
  </div>
</div>

app/views/bets/edit.html.erb
<h2>Edit Bet</h2>

<%= render "/bets/form", :bet => @bet %>

app/views/bets/feed.html.erb
<p>
  <%= render "/bets/display_bets", :bets => @bets %>
</p>

app/views/bets/show.html.erb
<h2>Bet show page</h2>
<div class="content group">
<div class="content-main">
  <div class="bets">
    <header class="group">
      <ul class="bets-list">
          <%= render "/bets/bet_detail", :bet => @bet %>
      </ul>
    </header>
  </div>
</div>
</div>