config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :update, :edit, :index] do
    member do
      get 'notifications'
      get 'refresh'
    end
    resources :friendships, :only => [:index, :create, :update, :destroy] do
      collection do
        get 'search_friends'
        get 'search'
        get 'pendings'
        post 'invite'
      end
    end
    resources :bets, :only => [:create, :new, :index] 
    resources :bet_participations, :only => [:update, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :bets, :only => [:show, :edit, :update] do
    resources :comments, only: [:create, :new, :show]
    member do
      get 'summary'
    end
    get 'community', on: :collection
    get 'pending', on: :collection
    get 'inplay', on: :collection
    get 'completed', on: :collection
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  root :to => 'users#index'
end

app/models/friendship.rb
#include Rails.application.routes.url_helpers

class Friendship < ActiveRecord::Base
  attr_accessible :in_friend_id, :out_friend_id, :pending_flag
  validates :in_friend, :out_friend, presence: true
  validates :in_friend_id, :uniqueness => {:scope => :out_friend_id}

  # before_save :check_recip_friendship_and_send_notifications

  belongs_to(
  :in_friend,
  class_name: "User",
  foreign_key: :in_friend_id,
  primary_key: :id
  )

  belongs_to(
  :out_friend,
  class_name: "User",
  foreign_key: :out_friend_id,
  primary_key: :id
  )

  def self.find_by_ids(out_friend_id, in_friend_id)
    Friendship.find_by_out_friend_id_and_in_friend_id(out_friend_id, in_friend_id)
  end

  def find_recip_friendship
    Friendship.find_by_in_friend_id_and_out_friend_id(self.out_friend_id, self.in_friend_id)
  end

  # def check_recip_friendship_and_send_notifications
  #   recip_friendship = self.find_recip_friendship
  #   if recip_friendship && recip_friendship.pending_flag
  #     Notification.create(user_id: out_friend.id, text: "#{self.out_friend.first_name} #{self.out_friend.last_name} accepted your friend request!", link: user_path(self.out_friend))
  #     recip_friendship.update_attribute(:pending_flag, false)
  #     self.pending_flag = false;
  #   else
  #     Notification.create(user_id: in_friend.id, text: "#{self.out_friend.first_name} #{self.out_friend.last_name} sent you a friend request!", link: user_friendships_path(self.in_friend))
  #   end
  #   true
  # end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_filter :require_admin_access!, :only => [:create, :destroy]

  def index
    @users = current_user.friends
    @users += current_user.outbound_pending_friends
    @users += current_user.inbound_pending_friends
    if request.xhr?
      render partial: 'friendships/show_details_lightbox', locals: {users: @users}
    else
      render partial: 'friendships/show_details_lightbox', locals: {users: @users}
    end
  end

  def search
    @user = current_user
    @users = User.search_by_name_and_email(params[:query])
    if request.xhr?
      render partial: 'friendships/show_details_lightbox', locals: {users: @users}
    else
      render partial: 'friendships/show_details_lightbox', locals: {users: @users}
    end
  end

  def create
    @friendship = Friendship.new(params[:friendship])
    @friendship.out_friend_id = current_user.id
    if @friendship.save
      check_recip_friendship_and_send_notifications(@friendship)
      if request.xhr?
        render partial: 'friendships/friendship_detail', locals: {user: @friendship.in_friend}
      else
        redirect_to user_friendships_url(current_user)
      end

    else
      render :json => "Can not save friendship"
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    if @friendship
      @other_user = @friendship.in_friend
      @friendship.find_recip_friendship.destroy
      @friendship.destroy
      if request.xhr?
        render partial: 'friendships/friendship_detail', locals: {user: @other_user}
      else
        redirect_to user_friendships_url(current_user)
      end
    else
      render :json => "Can not find friendship"
    end
  end

  def find

  end

  def search_friends
    @user = current_user
    @users = current_user.friends.search_by_name_and_email(params[:query])
    if request.xhr?
      render partial: 'friendships/drop_down_list', locals: {users: @users}
    else
      render partial: 'friendships/drop_down_list', locals: {users: @users}
    end
  end
  
  def pendings
    @pendings = current_user.inbound_pending_friends
    if request.xhr?
      render partial: 'friendships/show_details_lightbox', locals: {users: @pendings}
    else
      render partial: 'friendships/show_details_lightbox', locals: {users: @pendings}
    end
  end


  def invite
    new_user = User.find_by_username(params[:email])
    if new_user
      flash[:error] = "User already exists"
      redirect_to user_friendships_url(current_user)
    else
      new_user = User.new(username: params[:email])
      invite_email = UserMailer.invite_email(new_user, current_user)
      if invite_email.deliver
        flash[:notice] = "Invitation sent!"
      else
        flash[:error] = "Error in sending invitation email"
      end
    end

    redirect_to user_friendships_url(current_user)
  end

  def check_recip_friendship_and_send_notifications(friendship)
    recip_friendship = friendship.find_recip_friendship
    if recip_friendship && recip_friendship.pending_flag
      Notification.create(user_id: friendship.in_friend.id, text: "#{friendship.out_friend.first_name} #{friendship.out_friend.last_name} accepted your friend request!", link: user_url(friendship.out_friend))
      friendship.update_attribute(:pending_flag, false)
      recip_friendship.update_attribute(:pending_flag, false)
    else
      Notification.create(user_id: friendship.in_friend.id, text: "#{friendship.out_friend.first_name} #{friendship.out_friend.last_name} sent you a friend request!", link: pendings_user_friendships_url(friendship.in_friend))
    end
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_add_friendship_button.html.erb
<form class="add-friend-button" action="<%= user_friendships_url %>" method="post">
 <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

 <input
    type="hidden"
    name="friendship[in_friend_id]"
    value="<%= user.id %>">
 <input type="submit" value="<%= message %>">
</form>

app/views/friendships/_drop_down_form.html.erb
<form class="search-form trigger-search-query" action="<%= search_user_friendships_url(current_user.id) %>" data-remote="true" method="get">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

     <label for="search-query"></label>
     <input
     autocomplete="off"
     type="text"
     name="query"
     id="search-query"
     placeholder="example@gmail.com">

     <input type="submit" name="submit" value="Search">
  </form>

  <div class="search-drop-down hidden"></div>

app/views/friendships/_drop_down_list.html.erb
<% if users && users.count > 0 %>
<ul>
  <% users.each_with_index do |user, index| %>
  <li><a href="<%= user_url(user) %>" data-remote="true"><%= image_tag user.profile_pic.url(:thumb), :class => "search-pic" %><%= user.full_name %> (<%= user.username %>)</a></li>
    <% end %>
</ul>
<% end %>

app/views/friendships/_friendship_detail.html.erb
<div class="profile-picture">
	<a href='#'><%= image_tag user.profile_pic.url(:small), :id => "profile_pic" %></a>
</div>

<div class="profile-name trigger-user-show-form">
		<p>
			<span class="link-name"><a href="<%= user_url(user) %>" data-remote="true"><%= user.full_name%>: <%=  user.username %></a></span><br>
			<span class="friend-button">
<% if current_user.friends.include?(user) %>
   <!-- <%= button_to "Unfriend", user_friendship_url(current_user.id, current_user.find_friendship(user).id), remote: true, form_class: "unfriend-button", method: :delete %> -->
   <form class="unfriend-button" action="<%= user_friendship_url(current_user.id, current_user.find_friendship(user).id) %>" method="post">
    <input
       name="authenticity_token"
       type="hidden"
       value="<%= form_authenticity_token %>">

	<input name='_method' value='delete' type='hidden'>

    <input type="submit" value="Un-friend">
   </form>
   <% elsif current_user.outbound_pending_friends.include?(user) %>
   Friendship Pending...
   <% elsif current_user.inbound_pending_friends.include?(user) %>
     <%= render "add_friendship_button", :message => "Confirm Friend", :user => user %>
   <% else %>
     <%= render "add_friendship_button", :message => "Request Friendship", :user => user %>
     <% end %>
 </span>
</p>
</div>
  

app/views/friendships/_invite_user_form.html.erb
<form action="<%= invite_user_friendships_url(current_user) %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

     <label for="user_email">Invite a Friend: </label>
     <input
     type="text"
     name="email"
     id="user_email"
     placeholder="example@gmail.com">

     <input type="submit" value="Send Invite">
  </form>

app/views/friendships/_list_users.html.erb
<ul>
<% users.each do |user| %>
  <% unless user.id == current_user.id %>
    <li>
    <%= link_to "#{user.first_name} #{user.last_name}: #{user.username}", user_url(user) %>
    <% if @friends.include?(user) %>
       <%= button_to "Unfriend", user_friendship_url(current_user.id, current_user.find_friendship(user).id), method: :delete %>
       <% elsif @outbound_pending_friends.include?(user) %>
       Friendship Pending...
       <% elsif @inbound_pending_friends.include?(user) %>
         <%= render "add_friendship_button", :message => "Confirm Friend", :user => user %>
       <% else %>
         <%= render "add_friendship_button", :message => "Request Friendship", :user => user %>
         <% end %>
    </li>
    <% end %>
  <% end %>
</ul>

app/views/friendships/_show_details_lightbox.html.erb
<% friends = users.select { |user| current_user.friends.include?(user) } %>
<% unless friends.empty? %>
<h3>Current Friends</h3>
<ul class="current-friends-list group">
	<% friends.each do |friend| %>
	<li class="group">
	    <%= render "/friendships/friendship_detail", :user => friend %>
	</li>
	<% end %>
</ul>
<% end %>


<% pendings = users.select { |user| current_user.inbound_pending_friends.include?(user) || current_user.outbound_pending_friends.include?(user) } %>
<% unless pendings.empty? %>
<h3>Pending Friendshps</h3>
<ul class="pending-friends-list group">
	<% pendings.each do |pending| %>
	<li class="group">
	    <%= render "/friendships/friendship_detail", :user => pending %>
	</li>
	<% end %>
</ul>
<% end %>


<% others = users.select { |user| !friends.include?(user) && !pendings.include?(user) && (user != current_user) } %>
<% unless others.empty? %>
<h3>Other Users</h3>
<ul class="other-users-list group">
	<% others.each do |user| %>
	<li class="group">
	    <%= render "/friendships/friendship_detail", :user => user %>
	</li>
	<% end %>
</ul>
<% end %>

app/views/friendships/_show_lightbox.html.erb
<div class="friendship-show-form light-box-form hidden" id="friendship-show-form">
  <div class="form-header group" id="form-header">
    <span class="form-title">Friendship Show Page</span>
    <div class="x-button" id="x-button">x</div>
  </div>
  <div class="form-content group" id="friendship-show-content">
  </div>
</div>

app/views/friendships/index.html.erb
<h1>Friendship Index</h1>


<%= render "invite_user_form" %>

<h2>Existing Friends</h2>
<%= render "list_users", :users => @friends %>
<br>
<h2>Outbound Pending Friends</h2>
<%= render "list_users", :users => @outbound_pending_friends %>
<br>
<h2>Inbound Pending Friends</h2>
<%= render "list_users", :users => @inbound_pending_friends %>

<h2>All Users</h2>
<%= render "list_users", :users => User.all %>